<?php

/**
 * ChatMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChatMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChatMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChatMessage');
    }
}