<?php

/**
 * MeliOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MeliOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MeliOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MeliOrder');
    }
}