<?php

   /**
   * UserTable
   * 
   * This class has been auto-generated by the Doctrine ORM Framework
   */
   class UserTable extends Doctrine_Table
   {
      /**
      * Returns an instance of this class.
      *
      * @return object UserTable
      */
      public static function getInstance()
      {
         return Doctrine_Core::getTable('User');
      }

      public function createOrUpdate($user)
      {
         $existingUser = $this->findOneByMeliId($user->id);

         if(!$existingUser)
         {
            $existingUser = new User();
         }

         $existingUser->setMeliId($user->id);
         $existingUser->setUsername($user->nickname);
         $existingUser->setEmail($user->email);
         $existingUser->save();
      }
   }
