# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

order_detail: 
  url: /order/:id/detail
  param: { module: orders, action: detail }

messages:
  url: /order/:id/messages
  param: { module: orders, action: getMessages }

message_new:
  url: /order/newmessage
  param: { module: orders, action: newMessage }
  sf_requirements: 
    sf_method: [post]

homepage:
  url:   /
  param: { module: default, action: index }
