# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        true

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    web_debug:              false
    etag:                   false

all:
  .modules:
    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure
    
    error_404_module:       errors
    error_404_action:       error404

  .settings:
    rich_text_js_dir:   js/tiny_mce

    default_culture: es
    i18n: true  
  
    csrf_secret:            e9c73218ba5b74aeb2b1c609812dcd04d581cae3
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS
    lazy_cache_key:         true
    use_database:           true
    enabled_modules:        [default, sfGuardAuth, tmcContact]
    check_lock:             true

    standard_helpers:
      - Partial
      - PartialPlus
      - I18N
      - Date
      - Text
      - Number
      - ImageCache
