<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addlymediaasset extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ly_media_asset', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'folder_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'filename' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'author' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'copyright' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'type' => 
             array(
              'type' => 'string',
              'length' => 80,
             ),
             'filesize' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ly_media_asset');
    }
}