User:
  actAs:
    Timestampable: ~
  columns:
    meli_id: { type: string(255), notnull: true }
    username: { type: string(255), notnull: true }
    email: { type: string(255), notnull: true }

MeliOrder:
  actAs:
    Timestampable: ~
  columns:
    meli_order_id: { type: integer, notnull: true }
    item_id: { type: string(255), notnull: true }
    buyer_id: { type: integer, notnull: true }
    buyer_nickname: { type: string(255), notnull: true }
    buyer_email: { type: string(255), notnull: true }
    seller_id: { type: integer, notnull: true }
    seller_nickname: { type: string(255), notnull: true }
    seller_email: { type: string(255), notnull: true }
    date_created: { type: datetime, notnull: true }
    title: { type: string(255), notnull: true }
    quantity: { type: integer, notnull: true }
    unit_price: { type: float, notnull: true }
    currency_id: { type: string(10), notnull: true }
    thumbnail: { type: string(255) }
    status: { type: string(50), notnull: true }

ChatMessage:
  actAs:
    Timestampable: ~
  columns:
    meli_order_id: { type: integer, notnull: true }
    user_id: { type: integer, notnull: true }
    event_type: { type: string(50), notnull: true }
    message: { type: clob, notnull: true }
  relations:
    MeliOrder:
      onDelete: CASCADE
      foreignAlias: ChatMessages
    User:
      onDelete: CASCADE
      foreignAlias: ChatMessages
