User:
  actAs:
    Timestampable: ~
  columns:
    meli_id: { type: string(255), notnull: true }
    username: { type: string(255), notnull: true }
    email: { type: string(255), notnull: true }

MeliOrder:
  actAs:
    Timestampable: ~
  columns:
    meli_order_id: { type: string(255), notnull: true }

ChatMessage:
  actAs:
    Timestampable: ~
  columns:
    meli_order_id: { type: integer, notnull: true }
    user_id: { type: integer, notnull: true }
    message: { type: clob, notnull: true }
  relations:
    MeliOrder:
      onDelete: CASCADE
      foreignAlias: ChatMessages
    User:
      onDelete: CASCADE
      foreignAlias: ChatMessages
